### ISSUE TITLE
process not configured as a dependency, should it be?

### ISSUE THREAD

**Issue by chrisbarker** [tugberkugurlu/gulp-aspnet-k#30]
require('process') was erroring for me until I ran npm process 

Should it be in package.json or mentioned as a manually installed dependency?

**Comment by luisrudge** [comment]
Process is a native module. It doesn't need to be a dependency: https://nodejs.org/api/process.html

**Comment by chrisbarker** [comment]
Indeed it is. I tracked the issue down to vs2015 and where it looks for external tools with the help of this: http://blogs.msdn.com/b/webdev/archive/2015/03/19/customize-external-web-tools-in-visual-studio-2015.aspx, moving my path variable to the top so it started using the version of nodejs I had installed solved this problem for me. Thanks.

**Comment by luisrudge** [comment]
@chrisbarker thanks for the feedback!
