### ISSUE TITLE
rename

### ISSUE THREAD

**Issue by luisrudge** [tugberkugurlu/gulp-aspnet-k#9]
so, should we rename to gulp-dnx or gulp-aspnet-dnx? :)

**Comment by tugberkugurlu** [comment]
Yes, it probably makes sense. gulp-aspnet-dnx sounds good I think. Would you like to send the PR to reflect this name changes inside the codebase and the readme.

After the changes are done, I will rename the repo and publish the package with the new name.

Do you know how we can handle name changes in npm? Do we have a change to redirect the old name to this one?

**Comment by luisrudge** [comment]
I asked about the renaming here: https://twitter.com/luisrudge/status/602656409168273408

**Comment by luisrudge** [comment]
https://twitter.com/linclark/status/602916432481923072 not possible :(

**Comment by tugberkugurlu** [comment]
Ah, I see. deprecate should be OK then.

**Comment by ctolkien** [comment]
:+1: on gulp-dnx
